language: ruby
cache: bundler

addons:
  apt:
    packages:
      - docker-ce

script:
  - docker-compose build
  - docker-compose run app

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
      docker build -t u6kapps/investment-machine -f Dockerfile.production .;
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
      docker tag u6kapps/investment-machine u6kapps/investment-machine:$TRAVIS_TAG;
      docker push u6kapps/investment-machine;
    else
      echo skip docker push;
    fi

notifications:
  slack:
    secure: i6wGTuyxWwvEDtZzRL99D9Q4iO74bGOwkn+bR6a5gXiFyRkCKO6xGC/Cf6RkEkPKHhph1XLzM9yaTTMUSfc38UGpxUyQTE++QuONGvCRfzKtpayEAYu9hLQC9GmiZbUpw9A7M42/5p5N089bgzNbZ5SFdAMGWEMSOoS1EdfnUlmxNXyaIUekTVjbm3+YeJW80+BGefPVg1OrMc6kZbuhfM5srVSzX9Qs3k6XGhPDlTpBHT+PhDArhaMDNotX3VRWa9gz6FR/N90HfijPYL41hy+K420XsOjbSynEj0surdrn9QzTUI2LWktpaRSj7ACUr7HHG7icxqPqtxRcCQq+x1ae3bKmEvJl0jl1d/yadegG92ylXaNAw8/LvCTYXGUUN2rnK1OiTaSuYDjRclbnBhUzAhiY5m08jjHibFxV5UaL8GfSmCry4pCwig9kb0rNjpZlauZqvfjlTz9IApmXRb31Q2KV6gXx93O8SVDRFVy2sSDcR8tupMjXGHb93oh/ACCkELFqV7vU2m0JB87120UeauxmohyFnogRGv0HolEVb7cRI9gHQF3rhaS9yjH3pM6A+OgXN94N1bXekSCdLBnsGn5n42YzvlYdTJTYvV0XkKkzd860Lqtu8eb4VkxmYFR4d6BLnOq7KbtlluWyo6Jp+0RR7kLhP5cO63w0N9A=

