version: '3'

services:
  app:
    build: .
    environment:
      - "RAILS_ENV=development"
      - "DB_HOST=db"
      - "DB_USERNAME=db_user"
      - "DB_PASSWORD=db_pass"
      - "DB_DATABASE=db"
    volumes:
      - ".:/var/myapp"
    depends_on:
      - "db"
    ports:
      - "3000:3000"
  db:
    image: postgres:10
    environment:
      - "POSTGRES_USER=db_user"
      - "POSTGRES_PASSWORD=db_pass"
      - "POSTGRES_DB=db"
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db:
    driver: local
