version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      - "AWS_S3_ACCESS_KEY=s3_access_key"
      - "AWS_S3_SECRET_KEY=s3_secret_key"
      - "AWS_S3_REGION=my_region"
      - "AWS_S3_BUCKET=test.investment-stocks"
      - "AWS_S3_ENDPOINT=http://s3:9000"
      - "AWS_S3_FORCE_PATH_STYLE=true"
      - "DB_DATABASE=db"
      - "DB_USERNAME=db_user"
      - "DB_PASSWORD=db_pass"
      - "DB_HOST=db"
      - "DB_PORT=5432"
      #- "DB_SSLMODE=require"
      - "CRAWLINE_LOGGER_LEVEL=FATAL"
      - "INVESTMENT_LOGGER_LEVEL=INFO"

networks:
  default:
    external:
      name: production
