FROM ruby:2.6
LABEL maintainer="u6k.apps@gmail.com"

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get clean && \
    gem install specific_install && \
    gem specific_install -l "https://github.com/u6k/crawline.git" && \
    gem specific_install -l "https://github.com/u6k/investment-stocks-crawler.git"

ENTRYPOINT ["investment-stocks-crawler"]

