FROM ruby:2.6
LABEL maintainer="u6k.apps@gmail.com"

COPY . /var/myapp
WORKDIR /var/myapp

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get clean && \
    bundle install

ENTRYPOINT ["bundle", "exec", "investment-stocks-crawler"]

