# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6dc56ab58c1a99df1df75d7603c301e49f0254f8ea9011d8488e248775a9830d7a05c6844ee1a94d962b8c3cb1011b3969b736b03aa7061bb437e0bf05df8cdb

test:
  secret_key_base: 210249c48d1f853da0fcef27e9ef0b03aeaef07c14eded928c2c0e9406b2ff2b3283e5ca03f168a1ebad79ca1355ebdb7242a15556357d83b5c6e4666f3042fc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
